name: 'Branch Issue'
description: 'Get the issue associated with the branch'

inputs:
  github-token:
    description: 'GitHub token'
    required: true

outputs:
  issue-number:
    description: 'Extracted issue number from branch'
    value: ${{ steps.extract-issue.outputs.issue-number }}
  issue-exists:
    description: 'Whether the issue exists on GitHub'
    value: ${{ steps.check.outputs.issue-exists }}

runs:
  using: 'composite'
  steps:

    - name: Extract issue number from branch
      id: extract-issue
      shell: bash
      run: |
        BRANCH="${GITHUB_REF##*/}"
        echo "BRANCH=$BRANCH"
        ISSUE_NO=$(echo "$BRANCH" | cut -d"-" -f2| cut -d"." -f2)
        echo "ISSUE_NO=$ISSUE_NO"
        if [[ ! "$ISSUE_NO" =~ ^[0-9]+$ ]]; then
          echo "No issue number found in branch name: $BRANCH"
          echo "issue-number=" >> $GITHUB_OUTPUT
          exit 1
        fi
        # Extract type label (e.g., 'type:bug')

        echo "Branch name: $BRANCH"
        echo "Found issue number: $ISSUE_NO"
        echo "issue-number=$ISSUE_NO" >> $GITHUB_OUTPUT

    - name: Check if GitHub issue exists
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        REPO="${{ github.repository }}"
        ISSUE_NO=${{ steps.extract-issue.outputs.issue-number }}

        ISSUE_URL="https://api.github.com/repos/$REPO/issues/$ISSUE_NO"
        
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          $ISSUE_URL)

        if [ "$STATUS_CODE" -eq 200 ]; then
          echo "✅ Issue #$ISSUE_NO exists in $REPO"
          echo "issue-exists=true" >> $GITHUB_OUTPUT
          echo "### GitHub Branch created from issue : ✅ [#${ISSUE_NO}]($ISSUE_URL)" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Issue #$ISSUE_NO does NOT exist in $REPO (HTTP $STATUS_CODE)"
          echo "issue-exists=false" >> $GITHUB_OUTPUT
          echo "### GitHub Branch created from issue : ❌ Issue [#${ISSUE_NO}]($ISSUE_URL) not found" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
